<?php
$e = static fn($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$activeJokis = $db->query("SELECT id, nama, whatsapp, keahlian FROM joki WHERE status = 'aktif' ORDER BY nama")->fetchAll();
?>
<style>
.allocation-intro{margin-bottom:20px}.allocation-intro p{margin:7px 0 0;color:var(--muted)}.allocation-card{margin-bottom:16px}.allocation-card .panel-head{align-items:flex-start}.allocation-meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:7px;color:var(--muted);font-size:12px}.allocation-meta span{display:inline-flex;align-items:center;gap:5px}.allocation-select{min-width:190px;padding:10px 12px;border:1px solid var(--line);border-radius:8px;background:#fff;color:var(--ink);font:inherit}.allocation-table td{vertical-align:middle}.allocation-table td:first-child strong{font-family:'Space Grotesk',sans-serif}.allocation-table .btn{white-space:nowrap}@media(max-width:700px){.allocation-table{min-width:760px}}
</style>
<div class="allocation-intro"><h2>Bagikan tugas kepada joki</h2><p>Daftar ini berisi order aktif yang belum memiliki pengerja.</p></div>
<?php if ($allocationWhatsapp): ?><div class="alert"><i class="fa-brands fa-whatsapp"></i> Order berhasil dialokasikan. <a class="btn small" target="_blank" rel="noopener" href="<?= $e($allocationWhatsapp) ?>">Kirim detail ke WhatsApp <i class="fa-solid fa-arrow-up-right-from-square"></i></a></div><?php endif; ?>
<div class="panel allocation-card"><div class="table-wrap"><table class="allocation-table"><thead><tr><th>Order</th><th>Layanan / kategori</th><th>Deadline</th><th>Total</th><th>Pilih joki</th><th>Aksi</th></tr></thead><tbody>
<?php foreach ($allocationOrders as $order): ?><tr><td><strong><?= $e($order['order_code']) ?></strong><small><?= $e($order['customer_name']) ?></small></td><td><?= $e($order['service_title']) ?><small><?= $e($order['category_name']) ?></small></td><td><?= $order['deadline_at'] ? date('d M Y, H:i', strtotime($order['deadline_at'])) : '-' ?></td><td><strong><?= formatRupiah($order['total_price']) ?></strong><small>Bagian joki <?= formatRupiah(floor($order['total_price'] * .70)) ?></small></td><td><form id="alokasi-<?= (int) $order['id'] ?>" method="post" action="proses_alokasi.php"><input type="hidden" name="action" value="allocate"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><input type="hidden" name="order_id" value="<?= (int) $order['id'] ?>"><select class="allocation-select" name="joki_id" required><option value="">Pilih joki aktif</option><?php foreach ($activeJokis as $joki): ?><option value="<?= (int) $joki['id'] ?>"><?= $e($joki['nama']) ?> · <?= $e($joki['keahlian']) ?></option><?php endforeach; ?></select></form></td><td><button class="btn small" form="alokasi-<?= (int) $order['id'] ?>"><i class="fa-solid fa-share"></i> Alokasikan</button></td></tr><?php endforeach; ?>
<?php if (!$allocationOrders): ?><tr><td colspan="6" class="empty"><i class="fa-solid fa-circle-check"></i> Semua order aktif sudah memiliki joki.</td></tr><?php endif; ?></tbody></table></div></div>
<div class="allocation-intro assigned-heading"><h2>Order yang sedang dikerjakan</h2><p>Gunakan tombol ganti jika penjoki sebelumnya berhalangan mengerjakan.</p></div>
<div class="panel allocation-card"><div class="table-wrap"><table class="allocation-table"><thead><tr><th>Order</th><th>Layanan</th><th>Deadline</th><th>Penjoki saat ini</th><th>Ganti ke</th><th>Aksi</th></tr></thead><tbody>
<?php foreach ($assignedOrders as $order): ?><tr><td><strong><?= $e($order['order_code']) ?></strong><small><?= $e($order['customer_name']) ?></small></td><td><?= $e($order['service_title']) ?><small><?= $e($order['category_name']) ?></small></td><td><?= $order['deadline_at'] ? date('d M Y, H:i', strtotime($order['deadline_at'])) : '-' ?></td><td><strong><?= $e($order['joki_name']) ?></strong><small>Diproses joki</small></td><td><form id="ganti-<?= (int) $order['id'] ?>" method="post" action="proses_alokasi.php"><input type="hidden" name="action" value="replace"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><input type="hidden" name="order_id" value="<?= (int) $order['id'] ?>"><select class="allocation-select" name="joki_id" required><option value="">Pilih pengganti</option><?php foreach ($activeJokis as $joki): ?><?php if ((int) $joki['id'] !== (int) $order['joki_id']): ?><option value="<?= (int) $joki['id'] ?>"><?= $e($joki['nama']) ?> · <?= $e($joki['keahlian']) ?></option><?php endif; ?><?php endforeach; ?></select></form></td><td><button class="btn small" form="ganti-<?= (int) $order['id'] ?>"><i class="fa-solid fa-arrows-rotate"></i> Ganti</button></td></tr><?php endforeach; ?>
<?php if (!$assignedOrders): ?><tr><td colspan="6" class="empty">Belum ada order yang sedang dikerjakan.</td></tr><?php endif; ?></tbody></table></div></div>
