<style>.order-decision{display:inline-flex;align-items:center;gap:9px;margin:0 10px 0 0;vertical-align:middle}.order-decision form{display:inline-flex;align-items:center;margin:0}.order-decision .btn{position:relative;display:inline-flex;align-items:center;justify-content:center;width:34px;height:34px;padding:0;border:2px solid rgba(255,255,255,.9);border-radius:50%;font-size:0;line-height:1;background:#168653;color:#fff;box-shadow:0 4px 10px rgba(22,134,83,.2),0 0 0 1px rgba(22,134,83,.08);transition:transform .18s ease,box-shadow .18s ease,background .18s ease}.order-decision .btn i{position:absolute;inset:0;display:grid;place-items:center;width:auto;height:auto;margin:0;font-size:13px;line-height:1;text-align:center}.order-decision .btn:hover{background:#117044;box-shadow:0 7px 14px rgba(22,134,83,.28),0 0 0 3px rgba(22,134,83,.1);transform:translateY(-2px)}.order-decision .btn:focus-visible{outline:3px solid rgba(22,134,83,.25);outline-offset:2px}.order-decision .danger{background:#c9364a;color:#fff;box-shadow:0 4px 10px rgba(201,54,74,.2),0 0 0 1px rgba(201,54,74,.08)}.order-decision .danger:hover{background:#aa2d3e;box-shadow:0 7px 14px rgba(201,54,74,.28),0 0 0 3px rgba(201,54,74,.1);transform:translateY(-2px)}.order-decision .danger:focus-visible{outline-color:rgba(201,54,74,.25)}.order-actions{display:inline-flex;align-items:center;gap:6px;flex-wrap:nowrap}.order-actions form{display:flex;align-items:center;gap:6px}.order-actions select{min-width:130px}.table-wrap td:last-child{white-space:nowrap}.table-wrap td:last-child>.inline{display:inline-flex;vertical-align:middle}</style>
<div class="table-wrap">
  <table>
    <thead><tr><th>Order</th><th>Pelanggan</th><th>Layanan</th><th>Total</th><th>Status</th><th>Aksi</th></tr></thead>
    <tbody>
      <?php if (!$orders): ?>
        <tr><td colspan="6" class="empty">Belum ada pesanan yang cocok.</td></tr>
      <?php else: foreach ($orders as $order): ?>
        <?php
        $statusText = $statusLabels[$order['status']] ?? $order['status'];
        $statusUrl = SITE_URL . 'status.php?order=' . rawurlencode($order['order_code']);
        $whatsappMessage = "Halo {$order['customer_name']},\n\nUpdate pesanan Anda:\n- Kode order: {$order['order_code']}\n- Status: {$statusText}\n\nKlik link berikut untuk melihat status pesanan:\n{$statusUrl}\n\nSimpan kode order ini untuk pengecekan berikutnya. Jika membutuhkan bantuan, balas pesan ini dan admin kami akan membantu. Terima kasih telah mempercayai Velocity System AI.";
        ?>
        <tr>
          <td><strong><?= $e($order['order_code']) ?></strong><small>Masuk: <?= date('d M Y, H:i', strtotime($order['created_at'])) ?></small><small>Deadline: <?= !empty($order['deadline_at']) ? date('d M Y, H:i', strtotime($order['deadline_at'])) : '-' ?></small><?php if (!empty($order['shipping_required'])): ?><small><i class="fa-solid fa-truck-fast"></i> Kirim ke <?= $e($order['shipping_city']) ?> · <?= $e($order['shipping_courier']) ?></small><?php endif; ?><?php if (!empty($order['file_attachment'])): ?><small><a href="<?= $e(SITE_URL . 'public/uploads/' . rawurlencode($order['file_attachment'])) ?>" target="_blank" rel="noopener"><i class="fa-solid fa-paperclip"></i> Lampiran</a></small><?php endif; ?></td>
          <td><strong><?= $e($order['customer_name']) ?></strong><small><?= $e($order['whatsapp']) ?></small><?php if ($order['status'] === 'revisi' && !empty($order['revision_note'])): ?><small class="revision-note"><strong>Catatan:</strong> <?= $e($order['revision_note']) ?></small><?php endif; ?></td>
          <td><?= $e($order['service_title']) ?><small><?= (int) $order['quantity'] ?> unit</small><?php if (!empty($order['joki_name'])): ?><small><i class="fa-solid fa-user-pen"></i> Joki: <?= $e($order['joki_name']) ?><?php if (($order['joki_status'] ?? '') === 'suspend'): ?> (Suspend)<?php endif; ?></small><?php else: ?><small class="revision-alert">Belum ada joki</small><?php endif; ?></td>
          <td><strong><?= formatRupiah($order['total_price']) ?></strong><?php if (!empty($order['shipping_cost'])): ?><small>Termasuk ongkir <?= formatRupiah($order['shipping_cost']) ?></small><?php endif; ?><small>DP <?= formatRupiah($order['dp_amount']) ?></small></td>
          <td><span class="status <?= $e($order['status']) ?>"><?= $e($statusText) ?></span><?php if ($order['status'] === 'revisi'): ?><small class="revision-alert"><i class="fa-solid fa-pen-to-square"></i> Permintaan revisi baru<?php if (!empty($order['revision_requested_at'])): ?> · <?= date('d M H:i', strtotime($order['revision_requested_at'])) ?><?php endif; ?></small><?php endif; ?></td>
          <td><?php if (($order['approval_status'] ?? 'pending') === 'pending'): ?><div class="order-decision"><form method="post"><input type="hidden" name="action" value="approve_order"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><input type="hidden" name="order_id" value="<?= $order['id'] ?>"><button class="btn small" title="Terima pesanan"><i class="fa-solid fa-check"></i> ACC</button></form><form method="post" onsubmit="return confirm('Tolak pesanan ini?')"><input type="hidden" name="action" value="reject_order"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><input type="hidden" name="order_id" value="<?= $order['id'] ?>"><button class="btn small danger" title="Tolak pesanan"><i class="fa-solid fa-xmark"></i> Tolak</button></form></div><?php endif; ?><form class="inline" method="post"><input type="hidden" name="action" value="update_status"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><input type="hidden" name="order_id" value="<?= $order['id'] ?>"><select name="status"><?php foreach ($statusLabels as $key => $label): ?><option value="<?= $key ?>" <?= $order['status'] === $key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach; ?></select><button class="btn small" title="Simpan status"><i class="fa-solid fa-check"></i></button><a class="btn small light" target="_blank" href="https://wa.me/<?= formatWhatsAppNumber($order['whatsapp']) ?>?text=<?= rawurlencode($whatsappMessage) ?>" title="Kirim update via WhatsApp"><i class="fa-brands fa-whatsapp"></i></a><?php if ($order['status'] === 'selesai'): ?><a class="btn small light" target="_blank" href="invoice.php?id=<?= (int) $order['id'] ?>" title="Download invoice"><i class="fa-solid fa-file-invoice"></i></a><?php endif; ?></form></td>
        </tr>
      <?php endforeach; endif; ?>
    </tbody>
  </table>
</div>
