<?php $e = static fn($value): string => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); ?><style>
.joki-toolbar{display:grid;grid-template-columns:minmax(0,1fr) 220px;align-items:end;gap:12px;margin-bottom:18px}.joki-toolbar .search{max-width:none}.joki-filter-field{display:grid;gap:6px;color:var(--muted);font-size:12px;font-weight:700}.joki-filter-field select{width:100%;height:43px}.joki-panel .panel-head{padding:22px 24px}.joki-panel table{min-width:820px}.joki-panel th{white-space:nowrap}.joki-panel td{padding-top:18px;padding-bottom:18px;vertical-align:middle}.joki-panel td:first-child strong{font-family:'Space Grotesk',sans-serif;font-size:15px}.joki-panel .status{font-size:12px;font-weight:700}.joki-actions{display:flex;align-items:center;gap:7px}.joki-actions form{display:inline}.joki-actions .btn{min-width:36px}.modal-panel{display:none;position:fixed;inset:0;z-index:20;overflow-y:auto;background:rgba(23,35,46,.5);padding:7vh 16px 30px}.modal-panel.open{display:block}.modal-panel .modal-box{width:min(500px,100%);max-height:86vh;overflow-y:auto;margin:auto;padding:0 26px 26px;background:#fff;border:1px solid rgba(220,229,233,.9);border-radius:12px;box-shadow:0 20px 60px rgba(23,35,46,.2)}.modal-panel .panel-head{position:sticky;top:0;margin:0 -26px 22px;padding:20px 26px 16px;background:#fff;border-bottom:1px solid var(--line);z-index:1}.modal-panel form{display:grid;gap:14px}.modal-panel label{display:block;margin-bottom:6px;font-weight:600}.modal-panel input,.modal-panel select{width:100%;padding:10px 12px;border:1px solid var(--line);border-radius:8px;font:inherit}.modal-panel input:focus,.modal-panel select:focus{outline:0;border-color:var(--teal);box-shadow:0 0 0 3px rgba(0,124,131,.1)}.modal-close{border:0;background:transparent;font-size:24px;color:var(--muted);cursor:pointer}.modal-close:hover{color:var(--ink)}
@media(max-width:650px){.joki-toolbar{grid-template-columns:1fr;align-items:stretch}.joki-filter-field select{width:100%}.joki-panel .panel-head{padding:18px}.joki-panel td{padding-top:14px;padding-bottom:14px}.modal-panel{padding:18px 10px}.modal-panel .modal-box{max-height:calc(100vh - 36px);padding:0 18px 20px}.modal-panel .panel-head{margin:0 -18px 18px;padding:17px 18px 14px}}
</style>
<div class="toolbar joki-toolbar">
  <form class="search" method="get">
    <input type="hidden" name="tab" value="joki">
    <input type="hidden" name="keahlian" value="<?= $e($jokiFilter) ?>">
    <input name="q" value="<?= $e($jokiSearch) ?>" placeholder="Cari nama joki">
    <button class="btn"><i class="fa-solid fa-search"></i> Cari</button>
  </form>
  <label class="joki-filter-field">Keahlian
    <select onchange="this.form.submit()" form="joki-filter" name="keahlian">
      <option value="">Semua keahlian</option>
      <?php foreach ($jokiOptions as $option): ?><option value="<?= $e($option) ?>" <?= $jokiFilter === $option ? 'selected' : '' ?>><?= $e($option) ?></option><?php endforeach; ?>
    </select>
  </label>
  <form id="joki-filter" method="get"><input type="hidden" name="tab" value="joki"><input type="hidden" name="q" value="<?= $e($jokiSearch) ?>"></form>
</div>
<div class="panel joki-panel">
  <div class="panel-head"><h2>Daftar joki</h2><button class="btn" data-modal="joki-create"><i class="fa-solid fa-plus"></i> Tambah joki</button></div>
  <div class="table-wrap"><table><thead><tr><th>Nama</th><th>WhatsApp</th><th>Keahlian</th><th>Status</th><th>Rating</th><th>Selesai</th><th>Saldo</th><th>Aksi</th></tr></thead><tbody>
  <?php foreach ($jokiRows as $joki): ?><tr><td><strong><?= $e($joki['nama']) ?></strong></td><td><?= $e($joki['whatsapp']) ?></td><td><?= $e($joki['keahlian']) ?></td><td><span class="status <?= $joki['status'] === 'aktif' ? 'selesai' : 'cancelled' ?>"><?= $e(ucfirst($joki['status'])) ?></span></td><td><?= number_format((float) $joki['rating'], 1) ?>/5</td><td><?= (int) $joki['total_selesai'] ?></td><td><strong><?= formatRupiah($joki['saldo_joki']) ?></strong></td><td><div class="joki-actions"><button class="btn small" data-modal="joki-edit-<?= (int) $joki['id'] ?>" title="Edit joki"><i class="fa-solid fa-pen"></i></button><form method="post"><input type="hidden" name="action" value="toggle_joki"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><input type="hidden" name="joki_id" value="<?= (int) $joki['id'] ?>"><button class="btn small light" title="Ubah status"><i class="fa-solid fa-power-off"></i></button></form></div></td></tr><?php endforeach; ?>
  <?php if (!$jokiRows): ?><tr><td colspan="8" class="empty">Belum ada data joki yang cocok.</td></tr><?php endif; ?></tbody></table></div>
</div>
<div class="modal-panel" id="joki-create"><div class="modal-box"><div class="panel-head"><h2>Tambah joki</h2><button class="modal-close" data-close-modal>&times;</button></div><form method="post"><input type="hidden" name="action" value="create_joki"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><?php $joki = []; include __DIR__ . '/joki-form-fields.php'; ?><button class="btn">Simpan joki</button></form></div></div>
<?php foreach ($jokiRows as $joki): ?><div class="modal-panel" id="joki-edit-<?= (int) $joki['id'] ?>"><div class="modal-box"><div class="panel-head"><h2>Edit joki</h2><button class="modal-close" data-close-modal>&times;</button></div><form method="post"><input type="hidden" name="action" value="update_joki"><input type="hidden" name="csrf" value="<?= $e(adminCsrf()) ?>"><input type="hidden" name="joki_id" value="<?= (int) $joki['id'] ?>"><?php include __DIR__ . '/joki-form-fields.php'; ?><button class="btn">Simpan perubahan</button></form></div></div><?php endforeach; ?>
<script>document.querySelectorAll('[data-modal]').forEach(function(button){button.addEventListener('click',function(){var modal=document.getElementById(button.dataset.modal);modal.classList.add('open');modal.querySelector('input:not([type="hidden"])').focus();});});document.querySelectorAll('[data-close-modal]').forEach(function(button){button.addEventListener('click',function(){button.closest('.modal-panel').classList.remove('open');});});document.querySelectorAll('.modal-panel').forEach(function(modal){modal.addEventListener('click',function(event){if(event.target===modal)modal.classList.remove('open');});});document.addEventListener('keydown',function(event){if(event.key==='Escape')document.querySelectorAll('.modal-panel.open').forEach(function(modal){modal.classList.remove('open');});});</script>
